### ISSUE TITLE
v03 Additions

### ISSUE THREAD

**Issue by brelkh** [NEProperties/website#8]
- [x] Add blog photos to blog page (order is numbered in file name)
- [x] Embed their portfolio websites with an iframe on new "Listings" page. No need title ([Natalie's link](https://r065026a.propnex.net/))
- [x] Add new "Videos" page with just "Coming Soon!" (order: Home, About Us, Videos, Listings, Blog, Contact Us)
- [x] "Find your home valuation" just above gold award insert find your home valuation button, (http://srx.sg/89PTy)
- [x] Remove NE snippets from home page
- [x] Make gold award rounded.
- [x] Follow Figma new design for home page (remove "why was NE formed" from aboutUs)
- [x] Blogs add photos to blog page, add preview, **get preview and PDF from Ethan
- [x] insert socials icons (IG, FB, YT, **get links!!)
- [x] contactUs map to target HDB Hub east wing instead of west wing
- [x] ContactUs page, "chat over coffee!" (change full stop to exclamation)

**Comment by bik-industries** [comment]
For contactUs map, couldnt find HDB Hub east wing, so just used the more general "HDB hub".
